#!/usr/bin/env bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eux

# Install dependencies
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew update
brew install git
brew cask install google-cloud-sdk
brew cask install docker
brew cask install visual-studio-code

# Smoke test
gcloud --version
git --version
docker --version
code --version

echo "Setup script complete"
