#!/usr/bin/env bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eux

sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates gnupg git curl software-properties-common code docker-ce docker-ce-cli containerd.io

# Smoke test
gcloud --version
git --version
docker --version
code --version
